### ISSUE TITLE
Could not load BanManager-WebEnhancer

### ISSUE THREAD

**Issue by Hiobi** [BanManagement/BanManager-WebEnhancer#4]
Hi Confuser,

I'm trying to use your new WebUI (merged with AP), following your setup guide.
Is it compatible with BanManager v7?
**Steps**
* Download WebEnhancer #3 https://ci.frostcast.net/job/BanManager-WebEnhancer/3/
* Put in `/plugins` folder
* Launch the PaperMC server
* Error "Could not load ..."

**Details**
* **Server Software4**: PaperMC 1.15.2 R0.1 #146 
* **BanManager Version4**: BanManager v7.0

```
Could not load 'plugins/BanManager-WebEnhancer.jar' in folder 'plugins'
paperMC    | org.bukkit.plugin.UnknownDependencyException: BanManager
paperMC    | 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[paperspigot.jar:git-Paper-161]
paperMC    | 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) ~[paperspigot.jar:git-Paper-161]
paperMC    | 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[paperspigot.jar:git-Paper-161]
paperMC    | 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[paperspigot.jar:git-Paper-161]
paperMC    | 	at java.lang.Thread.run(Thread.java:834) [?:?]

```

Thanks !

**Comment by confuser** [comment]
Not yet, #1. There's a PR in progress to support it #3

**Comment by Hiobi** [comment]
Thanks !
