### ISSUE TITLE
Could not load 'plugins/BanManager-WebEnhancer.jar'

### ISSUE THREAD

**Issue by GoedendagMC** [BanManagement/BanManager-WebEnhancer#5]
[22:36:02 WARN]: Legacy plugin BanManager-WebEnhancer v1.0.0 does not specify an api-version.
[22:36:02 ERROR]: Could not load 'plugins/BanManager-WebEnhancer.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/confuser/banmanager/bukkitutil/BukkitPlugin
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:387) ~[patched_1.16.2.jar:git-Paper-160]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.2.jar:git-Paper-160]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-160]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-160]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NoClassDefFoundError: me/confuser/banmanager/bukkitutil/BukkitPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_265]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_265]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_265]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-160]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_265]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_265]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.2.jar:git-Paper-160]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: me.confuser.banmanager.bukkitutil.BukkitPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_265]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-160]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_265]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_265]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_265]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-160]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_265]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_265]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.2.jar:git-Paper-160]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.2.jar:git-Paper-160]
        ... 7 more

1.16.2 PaperMC server, BanManager 7.2.2

**Comment by confuser** [comment]
Resolved
